org.gradle.jvmargs=-Xmx1536M
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=1.21.1
neo_version=21.1.252
mod_id=kronwerke
mod_name=Kronwerke Core
mod_version=0.15.1
mod_group_id=de.kronwerke
mod_authors=Kronwerke
mod_description=Server framework for the Kronwerke community: whitelist slots, community goals and staged progression.
jei_version=19.57.0.449
chapters_version=jm7ojo3K
